### ISSUE TITLE
New message appears at each interval 

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/qgis-custom-news-feed#53]
Beobachtet:
Eine neue Meldung liegt vor, der Publizierungszeitraum ist aktuell. Die Meldung wird zu jedem Interval-Zeitpunkt als neu gemeldet und das Panel geöffnet.

Erwartet:
Die Meldung erscheint nur beim ersten mal, anschliessend wird die Meldung als gelesen betrachtet.

**Comment by tschumpr** [comment]
Kann ich nicht nachvollziehen, evt mit https://github.com/GeoWerkstatt/qgis-custom-news-feed/pull/58 behoben

**Comment by olivergrimm** [comment]
fixed
