### ISSUE TITLE
Panel opens with zero unread messages

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/qgis-custom-news-feed#54]
Beobachtet:
In der JSON-Datei existieren mehrere Meldungen für den aktuellen Zeitraum, jedoch sind alle als gelesen markiert. Zum Interval-Zeitpunkt öffnet sich das Panel trotzdem.

Erwartet:
Nur neue, ungelesene Meldungen sollen als neue Meldungen erkannt und behandelt werden.

**Comment by tschumpr** [comment]
Kann ich nicht nachvollziehen, evt. mit https://github.com/GeoWerkstatt/qgis-custom-news-feed/pull/58 behoben.

**Comment by olivergrimm** [comment]
fixed
