### ISSUE TITLE
Panel opens independent of the related setting

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/qgis-custom-news-feed#55]
Beobachtet:
Die Einstellung, dass im Falle neuer Meldungen das Panel geöffnet werden soll ist deaktiviert:
![image](https://github.com/GeoWerkstatt/qgis-custom-news-feed/assets/3465512/1f927254-e484-4435-b540-9e174fe6d806)

Zum Aktualisierungszeitpunkt wird aber trotzdem das Panel geöffnet.

Erwartet:
Das Panel soll nicht geöffnet werden, wenn die entsprechende Einstellung gesetzt ist

**Comment by tschumpr** [comment]
Kann ich nicht nachvollziehen

**Comment by olivergrimm** [comment]
tritt mit jüngstem Fix nicht mehr auf
