### ISSUE TITLE
No MessageBar at Panel opening

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/qgis-custom-news-feed#56]
Beobachtet:
Eine neue Meldung wird  erfasst. Zum Zeitpunkt der Anzeigeaktualisierung (Interval) erscheint die MessageBar und das Panel wird geöffnet.

Erwartet:
Wenn das Panel für eine neue Meldung geöffnet wird, muss keine MessageBar angezeigt werden. Die MessageBar soll nur dann angezeigt werden, wenn die Einstellung gesetzt ist, dass das Panel nicht automatisch geöffnet werden soll.

**Comment by tschumpr** [comment]
Ich hab das bewusst so gemacht, damit man auch bei offenem Panel auf die neuen Nachrichten aufmerksam gemacht wird. Da die Messagebar nur sehr kurz angezeigt wird, finde ich es nicht störend, wenn sie zusätzlich zum Panel angezeigt wird.

**Comment by olivergrimm** [comment]
Ok, ja die Kunden haben dies schon früher mal explizit weggewünscht. Darum musste ichs eröffnen.

**Comment by tschumpr** [comment]
Also müssen folgende Szenarien gedeckt sein:

Checkbox in den Einstellungen ist _nicht_ gesetzt:
- Neue Nachricht, Panel ist geschlossen --> Messagebar wird angezeigt, Panel bleibt geschlossen
- Neue Nachricht, Panel ist offen, aber im hinteren Tab --> Messagebar wird angezeigt, Panel wird nicht in den Vordergrund gebracht
- Neue Nachricht, Panel ist offen --> Messagebar wird nicht angezeigt, Panel bleibt offen

Checkbox in den Einstellungen ist gesetzt:
- Neue Nachricht, Panel ist geschlossen --> Messagebar wird nicht angezeigt, Panel wird geöffnet
- Neue Nachricht, Panel ist offen, aber im hinteren Tab --> Messagebar wird nicht angezeigt, Panel wird in den Vordergrund gebracht
- Neue Nachricht, Panel ist offen --> Messagebar wird nicht angezeigt, Panel bleibt offen

@olivergrimm Ist das so korrekt oder was fehlt?

**Comment by olivergrimm** [comment]
@tschumpr Danke für diese Zusammenstellung. Ja, das passt so aus meiner Sicht.
